#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$idCard = Ofcold\IdentityCard\IdentityCard::make('142701198003124054', 'en');

if ( $idCard === false ) {
	//	身份证号码不正确
	//	return
}

print_r($idCard->toArray());

